In [25]:
print("saakchee")

saakchee

In [26]:
import pandas as pd
import seaborn as sns
df= sns.load_dataset('tips')

In [32]:
from sklearn.preprocessing import LabelEncoder
encoder_time = LabelEncoder()

encoded_data = encoder_time.fit_transform(df['time'])

print('classes', encoder_time.classes_)

classes ['Dinner' 'Lunch']

In [29]:
for category, number in zip(encoder_time.classes_, range(len(encoder_time.classes_))):
    print(category,'------------', number)

Dinner ------------ 0
Lunch ------------ 1

In [31]:
encoder_day = LabelEncoder()

encoded_day_data = encoder_day.fit_transform(df['day'])
print('classes', encoder_day.classes_)

classes ['Fri' 'Sat' 'Sun' 'Thur']

In [33]:
for category, number in zip(encoder_day.classes_, range(len(encoder_day.classes_))):
    print(category,'------------', number)

Fri ------------ 0
Sat ------------ 1
Sun ------------ 2
Thur ------------ 3

In [35]:
encoder_day.inverse_transform([0,1,2,3])

array(['Fri', 'Sat', 'Sun', 'Thur'], dtype=object)

In [34]:
from sklearn.preprocessing import OneHotEncoder

In [41]:
ohe = OneHotEncoder(sparse_output= False, drop = 'first')
ohe_encoder=ohe.fit_transform(df[['sex','smoker']])

pd.DataFrame(ohe_encoder,columns=ohe.get_feature_names_out())

     sex_Male  smoker_Yes
0         0.0         0.0
1         1.0         0.0
2         1.0         0.0
3         1.0         0.0
4         0.0         0.0
..        ...         ...
239       1.0         0.0
240       0.0         1.0
241       1.0         1.0
242       1.0         0.0
243       0.0         0.0

[244 rows x 2 columns]

In [42]:
df1=pd.DataFrame(ohe_encoder,columns=ohe.get_feature_names_out())
pd.concat([df,df1],axis=1)

     total_bill   tip     sex smoker   day    time  size  sex_Male  smoker_Yes
0         16.99  1.01  Female     No   Sun  Dinner     2       0.0         0.0
1         10.34  1.66    Male     No   Sun  Dinner     3       1.0         0.0
2         21.01  3.50    Male     No   Sun  Dinner     3       1.0         0.0
3         23.68  3.31    Male     No   Sun  Dinner     2       1.0         0.0
4         24.59  3.61  Female     No   Sun  Dinner     4       0.0         0.0
..          ...   ...     ...    ...   ...     ...   ...       ...         ...
239       29.03  5.92    Male     No   Sat  Dinner     3       1.0         0.0
240       27.18  2.00  Female    Yes   Sat  Dinner     2       0.0         1.0
241       22.67  2.00    Male    Yes   Sat  Dinner     2       1.0         1.0
242       17.82  1.75    Male     No   Sat  Dinner     2       1.0         0.0
243       18.78  3.00  Female     No  Thur  Dinner     2       0.0         0.0

[244 rows x 9 columns]

In [49]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

In [54]:
log= FunctionTransformer(np.log10)
log.fit_transform(df['tip'])

0      0.004321
1      0.220108
2      0.544068
3      0.519828
4      0.557507
         ...
239    0.772322
240    0.301030
241    0.301030
242    0.243038
243    0.477121
Name: tip, Length: 244, dtype: float64

In [60]:
import numpy as np
from sklearn.preprocessing import PowerTransformer
x = np.array([
    [1],
    [1],
    [3],
    [5],
    [10],
    [50]
])

pt = PowerTransformer(method = "box-cox")

x_transformed = pt.fit_transform(x)

print("original:")
print(x.ravel())

print("\nTransformed:")
print(np.round(x_transformed.ravel(),3))

print("\nLearned lambda:")
print(pt.lambdas_)

original:
[ 1  1  3  5 10 50]

Transformed:
[-1.205 -1.205 -0.15   0.255  0.73   1.574]

Learned lambda:
[-0.23784507]

In [63]:
import pandas as pd
import numpy as np

# Sample customer dataset
data = {
    'Customer_ID': [101, 102, 103, 104, 105, 106, 107, 108],
    # Numerical columns with nulls
    'Age': [25, np.nan, 35, 42, np.nan, 29, 50, 38],
    'Annual_Income': [54000, 62000, np.nan, 85000, 71000, np.nan, 95000, 58000],
    'Credit_Score': [710, 680, 740, np.nan, 690, 720, 810, np.nan],
    # Categorical columns with nulls
    'Education': ['Bachelor', 'Master', 'Bachelor', np.nan, 'PhD', 'Master', np.nan, 'Bachelor'],
    'City': ['New York', np.nan, 'Chicago', 'Houston', np.nan, 'Miami', 'Chicago', 'New York'],
    'Employment_Status': ['Employed', 'Self-Employed', np.nan, 'Employed', 'Employed', np.nan, 'Self-Employed', 'Employed'],
    # Target / Full column
    'Purchased': ['Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No']
}

df = pd.DataFrame(data)

df

,Customer_ID,Age,Annual_Income,Credit_Score,Education,City,Employment_Status,Purchased
0,101,25.0,54000.0,710.0,Bachelor,New York,Employed,Yes
1,102,NaN,62000.0,680.0,Master,NaN,Self-Employed,No
2,103,35.0,NaN,740.0,Bachelor,Chicago,NaN,No
3,104,42.0,85000.0,NaN,NaN,Houston,Employed,Yes
4,105,NaN,71000.0,690.0,PhD,NaN,Employed,Yes
5,106,29.0,NaN,720.0,Master,Miami,NaN,No
6,107,50.0,95000.0,810.0,NaN,Chicago,Self-Employed,Yes
7,108,38.0,58000.0,NaN,Bachelor,New York,Employed,No

In [72]:
from sklearn.impute import SimpleImputer

imputer_mean = SimpleImputer(strategy='mean')

imputer_mean.fit_transform(df[['Annual_Income']])

array([[54000.        ],
       [62000.        ],
       [70833.33333333],
       [85000.        ],
       [71000.        ],
       [70833.33333333],
       [95000.        ],
       [58000.        ]])

In [73]:
df['new_salary']=imputer_mean.fit_transform(df[['Annual_Income']]).flatten()
df

,Customer_ID,Age,Annual_Income,Credit_Score,Education,City,Employment_Status,Purchased,new_salary
0,101,25.0,54000.0,710.0,Bachelor,New York,Employed,Yes,54000.000000
1,102,NaN,62000.0,680.0,Master,NaN,Self-Employed,No,62000.000000
2,103,35.0,NaN,740.0,Bachelor,Chicago,NaN,No,70833.333333
3,104,42.0,85000.0,NaN,NaN,Houston,Employed,Yes,85000.000000
4,105,NaN,71000.0,690.0,PhD,NaN,Employed,Yes,71000.000000
5,106,29.0,NaN,720.0,Master,Miami,NaN,No,70833.333333
6,107,50.0,95000.0,810.0,NaN,Chicago,Self-Employed,Yes,95000.000000
7,108,38.0,58000.0,NaN,Bachelor,New York,Employed,No,58000.000000

In [76]:
imputer_mode = SimpleImputer(strategy='most_frequent')
imputer_mode.fit_transform(df[['Age']])
df['new_age']=imputer_mode.fit_transform(df[['Age']]).flatten()
df

,Customer_ID,Age,Annual_Income,Credit_Score,Education,City,Employment_Status,Purchased,new_salary,new_age
0,101,25.0,54000.0,710.0,Bachelor,New York,Employed,Yes,54000.000000,25.0
1,102,NaN,62000.0,680.0,Master,NaN,Self-Employed,No,62000.000000,25.0
2,103,35.0,NaN,740.0,Bachelor,Chicago,NaN,No,70833.333333,35.0
3,104,42.0,85000.0,NaN,NaN,Houston,Employed,Yes,85000.000000,42.0
4,105,NaN,71000.0,690.0,PhD,NaN,Employed,Yes,71000.000000,25.0
5,106,29.0,NaN,720.0,Master,Miami,NaN,No,70833.333333,29.0
6,107,50.0,95000.0,810.0,NaN,Chicago,Self-Employed,Yes,95000.000000,50.0
7,108,38.0,58000.0,NaN,Bachelor,New York,Employed,No,58000.000000,38.0

In [78]:
imputer = SimpleImputer(strategy='most_frequent')
df['City']=imputer.fit_transform(df[['City']]).flatten()
df

,Customer_ID,Age,Annual_Income,Credit_Score,Education,City,Employment_Status,Purchased,new_salary,new_age
0,101,25.0,54000.0,710.0,Bachelor,New York,Employed,Yes,54000.000000,25.0
1,102,NaN,62000.0,680.0,Master,Chicago,Self-Employed,No,62000.000000,25.0
2,103,35.0,NaN,740.0,Bachelor,Chicago,NaN,No,70833.333333,35.0
3,104,42.0,85000.0,NaN,NaN,Houston,Employed,Yes,85000.000000,42.0
4,105,NaN,71000.0,690.0,PhD,Chicago,Employed,Yes,71000.000000,25.0
5,106,29.0,NaN,720.0,Master,Miami,NaN,No,70833.333333,29.0
6,107,50.0,95000.0,810.0,NaN,Chicago,Self-Employed,Yes,95000.000000,50.0
7,108,38.0,58000.0,NaN,Bachelor,New York,Employed,No,58000.000000,38.0